### ISSUE TITLE
mod_proxy not working

### ISSUE THREAD

**Issue by zeande** [acm-ndsu/NDSU-ACM-Website#1]
Apache's mod_proxy is no longer configured correctly on the web server. It used to be that you could view your personal site by browsing to http://ndacm.org/~uid, but now something is broken on one of the servers, and the proxy isn't working as it should.

**Comment by jghibiki** [comment]
uuuuuugh ok i can look into this tonight. In the mean time, routing through melt still works: http://melt.ndacm.org/zeande/

**Comment by jghibiki** [comment]
Well i have it working with UserDir which simply result in a redirect to melt.ndacm.org/<uid>/ still looking into the mod_proxy solution.

**Comment by EricWM612** [comment]
Sorry to send out a confusing email 3.5 years after you forgot this existed, but is this still an issue? I don't believe this system is still in use.

**Comment by zeande** [comment]
Oof. Na, I don't think that the old Apache server is still what's hosting the acm website, so this issue seems irrelevant at this point.

**Comment by jghibiki** [comment]
Yeah melt has been dead for a while because of the NFS issues we started running into. It was replaced after participating in a DDOS attack 🤣 and the  new server had issues. And for how few people were using it, it didn't seem worth the effort to fix it.

**Comment by EricWM612** [comment]
Good to know, thank you both for helping solve this years-old mystery!
